# Change these first
owner: iplanwebsites # Your GitHub organization or username, where this repository lives
repo: up # The name of this repository

sites:
  - name: Fragile ventures (web)
    url: https://fragile.ventures
 # - name: Wikipedia
 #   url: https://en.wikipedia.org
  - name: Lovely (brochure)
    url: https://lovely.link/
  - name: Lovely (img)
    url: https://img.lovely.link/v1/invitation/profile?title=title&text1=text1&text2=text2&text3=text3&avatar=https%3A%2F%2Frandomuser.me%2Fapi%2Fportraits%2Fwomen%2F67.jpg&rating5=0
  - name: Lovely (demo)
    url: https://demo.lovely.link/
  - name: Invitation (web)
    url: https://invitation.codes
  - name: Invitation (og.invt.co - v1)
    url: https://og.invt.co/felix.png?fontSize=%40felix&theme=light&md=1&images=https%3A%2F%2Flh3.googleusercontent.com%2Fa-%2FAOh14GjUk2VKmkWxpgWZgY0CXWRFi_k6t7f2MBSsfSxR%3Ds96-c
  - name: Kicking (web)
    url: https://kickinglotus.com/en
  - name: Kicking (recu)
    url: https://recu.kickinglotus.com/
  - name: CounterApi (brochure)
    url: https://counterapi.com/
  - name: NowBoarding (tokyo)
    url: https://tokyo.nowboarding.club/
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: up.fragile.ventures
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Up
  introTitle: "**Up** is an uptime monitor we use for a variety of internal tests and friends' projects."
  # introMessage: We monitor a variety of friends
  # introMessage: TShoot us an email if you'd like to monitor your site. required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
 #   - title: GitHub
 #     href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
